/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed Dec 26 23:33:06 EST 2018
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Family
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Product2_FamilyEnum {

    // None
    NONE("None");

    final String value;

    private Product2_FamilyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Product2_FamilyEnum fromValue(String value) {
        for (Product2_FamilyEnum e : Product2_FamilyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
